"""Added family member , Health record Models

Revision ID: 4118e53b0247
Revises: cb8b29f61f21
Create Date: 2025-06-13 17:22:19.839164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4118e53b0247'
down_revision = 'cb8b29f61f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_record')
    op.drop_table('family_member')
    # ### end Alembic commands ###
