"""Add email verification fields to User model

Revision ID: 9731cf1c4d83
Revises: 4118e53b0247
Create Date: 2025-06-15 13:58:51.102864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9731cf1c4d83'
down_revision = '4118e53b0247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_generated_at')
        batch_op.drop_column('otp')
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###
