"""Initial migration with consistent user table

Revision ID: a5cf0cea0f86
Revises: 
Create Date: 2025-06-30 16:15:47.631016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cf0cea0f86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='health_app_schema'
    )
    op.create_table('family_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['health_app_schema.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='health_app_schema'
    )
    op.create_table('health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['health_app_schema.family_member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='health_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_record', schema='health_app_schema')
    op.drop_table('family_member', schema='health_app_schema')
    op.drop_table('user', schema='health_app_schema')
    # ### end Alembic commands ###
